// Code generated by go-bindata.
// sources:
// assets/css/icons.css
// assets/css/style.css
// assets/css/tailwind.css
// assets/fonts/glyphicons-halflings-regular.eot
// assets/fonts/glyphicons-halflings-regular.svg
// assets/fonts/glyphicons-halflings-regular.ttf
// assets/fonts/glyphicons-halflings-regular.woff
// assets/fonts/glyphicons-halflings-regular.woff2
// assets/images/github.png
// assets/images/hog.png
// assets/js/angular-1.8.3.min.js
// assets/js/controllers.js
// assets/js/filesize-3.1.2.min.js
// assets/js/iso88591_map.js
// assets/js/jquery-1.11.0.min.js
// assets/js/jquery-ui-1.10.4.min.js
// assets/js/moment-2.8.4.js
// assets/js/punycode.js
// assets/js/sjis_map.js
// assets/js/strutil.js
// assets/templates/index.html
// assets/templates/layout.html
// DO NOT EDIT!

package assets

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := os.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// assetsCssIconsCss reads file data from disk. It returns an error on failure.
func assetsCssIconsCss() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/css/icons.css"
	name := "assets/css/icons.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsCssStyleCss reads file data from disk. It returns an error on failure.
func assetsCssStyleCss() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/css/style.css"
	name := "assets/css/style.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsCssTailwindCss reads file data from disk. It returns an error on failure.
func assetsCssTailwindCss() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/css/tailwind.css"
	name := "assets/css/tailwind.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsFontsGlyphiconsHalflingsRegularEot reads file data from disk. It returns an error on failure.
func assetsFontsGlyphiconsHalflingsRegularEot() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/fonts/glyphicons-halflings-regular.eot"
	name := "assets/fonts/glyphicons-halflings-regular.eot"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsFontsGlyphiconsHalflingsRegularSvg reads file data from disk. It returns an error on failure.
func assetsFontsGlyphiconsHalflingsRegularSvg() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/fonts/glyphicons-halflings-regular.svg"
	name := "assets/fonts/glyphicons-halflings-regular.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsFontsGlyphiconsHalflingsRegularTtf reads file data from disk. It returns an error on failure.
func assetsFontsGlyphiconsHalflingsRegularTtf() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/fonts/glyphicons-halflings-regular.ttf"
	name := "assets/fonts/glyphicons-halflings-regular.ttf"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsFontsGlyphiconsHalflingsRegularWoff reads file data from disk. It returns an error on failure.
func assetsFontsGlyphiconsHalflingsRegularWoff() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/fonts/glyphicons-halflings-regular.woff"
	name := "assets/fonts/glyphicons-halflings-regular.woff"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsFontsGlyphiconsHalflingsRegularWoff2 reads file data from disk. It returns an error on failure.
func assetsFontsGlyphiconsHalflingsRegularWoff2() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/fonts/glyphicons-halflings-regular.woff2"
	name := "assets/fonts/glyphicons-halflings-regular.woff2"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsImagesGithubPng reads file data from disk. It returns an error on failure.
func assetsImagesGithubPng() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/images/github.png"
	name := "assets/images/github.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsImagesHogPng reads file data from disk. It returns an error on failure.
func assetsImagesHogPng() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/images/hog.png"
	name := "assets/images/hog.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsJsAngular183MinJs reads file data from disk. It returns an error on failure.
func assetsJsAngular183MinJs() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/js/angular-1.8.3.min.js"
	name := "assets/js/angular-1.8.3.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsJsControllersJs reads file data from disk. It returns an error on failure.
func assetsJsControllersJs() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/js/controllers.js"
	name := "assets/js/controllers.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsJsFilesize312MinJs reads file data from disk. It returns an error on failure.
func assetsJsFilesize312MinJs() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/js/filesize-3.1.2.min.js"
	name := "assets/js/filesize-3.1.2.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsJsIso88591_mapJs reads file data from disk. It returns an error on failure.
func assetsJsIso88591_mapJs() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/js/iso88591_map.js"
	name := "assets/js/iso88591_map.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsJsJquery1110MinJs reads file data from disk. It returns an error on failure.
func assetsJsJquery1110MinJs() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/js/jquery-1.11.0.min.js"
	name := "assets/js/jquery-1.11.0.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsJsJqueryUi1104MinJs reads file data from disk. It returns an error on failure.
func assetsJsJqueryUi1104MinJs() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/js/jquery-ui-1.10.4.min.js"
	name := "assets/js/jquery-ui-1.10.4.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsJsMoment284Js reads file data from disk. It returns an error on failure.
func assetsJsMoment284Js() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/js/moment-2.8.4.js"
	name := "assets/js/moment-2.8.4.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsJsPunycodeJs reads file data from disk. It returns an error on failure.
func assetsJsPunycodeJs() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/js/punycode.js"
	name := "assets/js/punycode.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsJsSjis_mapJs reads file data from disk. It returns an error on failure.
func assetsJsSjis_mapJs() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/js/sjis_map.js"
	name := "assets/js/sjis_map.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsJsStrutilJs reads file data from disk. It returns an error on failure.
func assetsJsStrutilJs() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/js/strutil.js"
	name := "assets/js/strutil.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsTemplatesIndexHtml reads file data from disk. It returns an error on failure.
func assetsTemplatesIndexHtml() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/templates/index.html"
	name := "assets/templates/index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsTemplatesLayoutHtml reads file data from disk. It returns an error on failure.
func assetsTemplatesLayoutHtml() (*asset, error) {
	path := "/Users/sureshinde/GolandProjects/mailcache/mailcache-ui/assets/templates/layout.html"
	name := "assets/templates/layout.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"assets/css/icons.css": assetsCssIconsCss,
	"assets/css/style.css": assetsCssStyleCss,
	"assets/css/tailwind.css": assetsCssTailwindCss,
	"assets/fonts/glyphicons-halflings-regular.eot": assetsFontsGlyphiconsHalflingsRegularEot,
	"assets/fonts/glyphicons-halflings-regular.svg": assetsFontsGlyphiconsHalflingsRegularSvg,
	"assets/fonts/glyphicons-halflings-regular.ttf": assetsFontsGlyphiconsHalflingsRegularTtf,
	"assets/fonts/glyphicons-halflings-regular.woff": assetsFontsGlyphiconsHalflingsRegularWoff,
	"assets/fonts/glyphicons-halflings-regular.woff2": assetsFontsGlyphiconsHalflingsRegularWoff2,
	"assets/images/github.png": assetsImagesGithubPng,
	"assets/images/hog.png": assetsImagesHogPng,
	"assets/js/angular-1.8.3.min.js": assetsJsAngular183MinJs,
	"assets/js/controllers.js": assetsJsControllersJs,
	"assets/js/filesize-3.1.2.min.js": assetsJsFilesize312MinJs,
	"assets/js/iso88591_map.js": assetsJsIso88591_mapJs,
	"assets/js/jquery-1.11.0.min.js": assetsJsJquery1110MinJs,
	"assets/js/jquery-ui-1.10.4.min.js": assetsJsJqueryUi1104MinJs,
	"assets/js/moment-2.8.4.js": assetsJsMoment284Js,
	"assets/js/punycode.js": assetsJsPunycodeJs,
	"assets/js/sjis_map.js": assetsJsSjis_mapJs,
	"assets/js/strutil.js": assetsJsStrutilJs,
	"assets/templates/index.html": assetsTemplatesIndexHtml,
	"assets/templates/layout.html": assetsTemplatesLayoutHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"assets": &bintree{nil, map[string]*bintree{
		"css": &bintree{nil, map[string]*bintree{
			"icons.css": &bintree{assetsCssIconsCss, map[string]*bintree{}},
			"style.css": &bintree{assetsCssStyleCss, map[string]*bintree{}},
			"tailwind.css": &bintree{assetsCssTailwindCss, map[string]*bintree{}},
		}},
		"fonts": &bintree{nil, map[string]*bintree{
			"glyphicons-halflings-regular.eot": &bintree{assetsFontsGlyphiconsHalflingsRegularEot, map[string]*bintree{}},
			"glyphicons-halflings-regular.svg": &bintree{assetsFontsGlyphiconsHalflingsRegularSvg, map[string]*bintree{}},
			"glyphicons-halflings-regular.ttf": &bintree{assetsFontsGlyphiconsHalflingsRegularTtf, map[string]*bintree{}},
			"glyphicons-halflings-regular.woff": &bintree{assetsFontsGlyphiconsHalflingsRegularWoff, map[string]*bintree{}},
			"glyphicons-halflings-regular.woff2": &bintree{assetsFontsGlyphiconsHalflingsRegularWoff2, map[string]*bintree{}},
		}},
		"images": &bintree{nil, map[string]*bintree{
			"github.png": &bintree{assetsImagesGithubPng, map[string]*bintree{}},
			"hog.png": &bintree{assetsImagesHogPng, map[string]*bintree{}},
		}},
		"js": &bintree{nil, map[string]*bintree{
			"angular-1.8.3.min.js": &bintree{assetsJsAngular183MinJs, map[string]*bintree{}},
			"controllers.js": &bintree{assetsJsControllersJs, map[string]*bintree{}},
			"filesize-3.1.2.min.js": &bintree{assetsJsFilesize312MinJs, map[string]*bintree{}},
			"iso88591_map.js": &bintree{assetsJsIso88591_mapJs, map[string]*bintree{}},
			"jquery-1.11.0.min.js": &bintree{assetsJsJquery1110MinJs, map[string]*bintree{}},
			"jquery-ui-1.10.4.min.js": &bintree{assetsJsJqueryUi1104MinJs, map[string]*bintree{}},
			"moment-2.8.4.js": &bintree{assetsJsMoment284Js, map[string]*bintree{}},
			"punycode.js": &bintree{assetsJsPunycodeJs, map[string]*bintree{}},
			"sjis_map.js": &bintree{assetsJsSjis_mapJs, map[string]*bintree{}},
			"strutil.js": &bintree{assetsJsStrutilJs, map[string]*bintree{}},
		}},
		"templates": &bintree{nil, map[string]*bintree{
			"index.html": &bintree{assetsTemplatesIndexHtml, map[string]*bintree{}},
			"layout.html": &bintree{assetsTemplatesLayoutHtml, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = os.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

